
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ruedalo_backend
    restart: always
    expose:
      - "8000"
    env_file:
      - ./backend/.env

    networks:
      - ruedalo_net
      - rapippay_zinli-network

networks:
  ruedalo_net:
    driver: bridge
  rapippay_zinli-network:
    external: true
